pub mod app_icon;
pub mod audio;
pub mod autostart;
pub mod config;
pub mod hotkey;
pub mod inject;
pub mod overlay;
pub mod settings_ui;
#[cfg(feature = "transcribe-file")]
pub mod transcribe_ui;
pub mod tray;
pub mod whisper;
