#[cfg(feature = "gui")]
pub mod app_icon;
pub mod audio;
pub mod autostart;
pub mod config;
#[cfg(feature = "gui")]
pub mod fonts;
pub mod hotkey;
pub mod inject;
pub mod postprocess;
pub mod overlay;
#[cfg(feature = "gui")]
pub mod settings_ui;
#[cfg(feature = "transcribe-file")]
pub mod transcribe_ui;
pub mod tray;
pub mod whisper;
